package com.thunderslash.enumerations;

public enum SpriteType {
    NONE, PLAYER, PLAYER_DEAD,
    WATER, ERROR,
    WALL_SINGLE, WALL_FULL,
    WALL_90_DEGREE, WALL_ONE_SIDED, WALL_TWO_SIDED,
    WALL_CORNER, WALL_TWO_CORNER, WALL_THREE_SIDED,
    PLATFORM, WALL_FOUR_CORNER,
    
    BACKGROUND_TILE_01, BACKGROUND_TILE_02, 
    BACKGROUND_TILE_03, BACKGROUND_TILE_04,
    
    GATE_CLOSED, GATE_OPEN,
    SPIKES, LIGHT_CIRCLE,
    CHEST_CLOSED, CHEST_OPEN,
    ENEMY_SLIME, ENEMY_SLIME_DEAD,
    CRYSTAL, CRYSTAL_USED, 
    TORCH,
    
    DAGGER_BACKGROUND, 
    
    LIGHTNING_BOLT, 
   
}
