package com.thunderslash.enumerations;

public enum SpriteType {
    NONE, PLAYER, WATER, ERROR,
    WALL_SINGLE,
    WALL_90_DEGREE, WALL_ONE_SIDED, WALL_TWO_SIDED,
    WALL_CORNER, WALL_TWO_CORNER, WALL_THREE_SIDED,
    PLATFORM,
    BACKGROUND_TILE_01,
    DOOR_CLOSED, DOOR_OPEN,
    SPIKES, LIGHT_CIRCLE,
    CHEST_CLOSED, CHEST_OPEN,
    ENEMY_SLIME, 
    CRYSTAL, CRYSTAL_USED
    
}
